version: "3.9"

services:
  api:
    build: .
    command: uvicorn app.main:app
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
